// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/permission.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    uint64                 `protobuf:"varint,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  string                 `protobuf:"bytes,2,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	SubjectId     uint64                 `protobuf:"varint,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_common_proto_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_permission_proto_rawDescGZIP(), []int{0}
}

func (x *GetPermissionsRequest) GetIdentityId() uint64 {
	if x != nil {
		return x.IdentityId
	}
	return 0
}

func (x *GetPermissionsRequest) GetIdentityType() string {
	if x != nil {
		return x.IdentityType
	}
	return ""
}

func (x *GetPermissionsRequest) GetSubjectId() uint64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

type GetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_common_proto_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_permission_proto_rawDescGZIP(), []int{1}
}

func (x *GetPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_common_proto_permission_proto protoreflect.FileDescriptor

const file_common_proto_permission_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/proto/permission.proto\x12\rpermission.v1\"|\n" +
	"\x15GetPermissionsRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\x04R\n" +
	"identityId\x12#\n" +
	"\ridentity_type\x18\x02 \x01(\tR\fidentityType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\x04R\tsubjectId\":\n" +
	"\x16GetPermissionsResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions2r\n" +
	"\x11PermissionService\x12]\n" +
	"\x0eGetPermissions\x12$.permission.v1.GetPermissionsRequest\x1a%.permission.v1.GetPermissionsResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_common_proto_permission_proto_rawDescOnce sync.Once
	file_common_proto_permission_proto_rawDescData []byte
)

func file_common_proto_permission_proto_rawDescGZIP() []byte {
	file_common_proto_permission_proto_rawDescOnce.Do(func() {
		file_common_proto_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_permission_proto_rawDesc), len(file_common_proto_permission_proto_rawDesc)))
	})
	return file_common_proto_permission_proto_rawDescData
}

var file_common_proto_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_permission_proto_goTypes = []any{
	(*GetPermissionsRequest)(nil),  // 0: permission.v1.GetPermissionsRequest
	(*GetPermissionsResponse)(nil), // 1: permission.v1.GetPermissionsResponse
}
var file_common_proto_permission_proto_depIdxs = []int32{
	0, // 0: permission.v1.PermissionService.GetPermissions:input_type -> permission.v1.GetPermissionsRequest
	1, // 1: permission.v1.PermissionService.GetPermissions:output_type -> permission.v1.GetPermissionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_permission_proto_init() }
func file_common_proto_permission_proto_init() {
	if File_common_proto_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_permission_proto_rawDesc), len(file_common_proto_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_permission_proto_goTypes,
		DependencyIndexes: file_common_proto_permission_proto_depIdxs,
		MessageInfos:      file_common_proto_permission_proto_msgTypes,
	}.Build()
	File_common_proto_permission_proto = out.File
	file_common_proto_permission_proto_goTypes = nil
	file_common_proto_permission_proto_depIdxs = nil
}
