// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: common/proto/user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetClientById_FullMethodName           = "/user.v1.UserService/GetClientById"
	UserService_GetClientByIdentityId_FullMethodName   = "/user.v1.UserService/GetClientByIdentityId"
	UserService_GetEmployeeById_FullMethodName         = "/user.v1.UserService/GetEmployeeById"
	UserService_GetEmployeeByIdentityId_FullMethodName = "/user.v1.UserService/GetEmployeeByIdentityId"
	UserService_GetAllClients_FullMethodName           = "/user.v1.UserService/GetAllClients"
	UserService_GetAllActuaries_FullMethodName         = "/user.v1.UserService/GetAllActuaries"
	UserService_GetIdentityByUserId_FullMethodName     = "/user.v1.UserService/GetIdentityByUserId"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetClientById(ctx context.Context, in *GetClientByIdRequest, opts ...grpc.CallOption) (*GetClientByIdResponse, error)
	GetClientByIdentityId(ctx context.Context, in *GetClientByIdentityIdRequest, opts ...grpc.CallOption) (*GetClientByIdResponse, error)
	GetEmployeeById(ctx context.Context, in *GetEmployeeByIdRequest, opts ...grpc.CallOption) (*GetEmployeeByIdResponse, error)
	GetEmployeeByIdentityId(ctx context.Context, in *GetEmployeeByIdentityIdRequest, opts ...grpc.CallOption) (*GetEmployeeByIdResponse, error)
	GetAllClients(ctx context.Context, in *GetAllClientsRequest, opts ...grpc.CallOption) (*GetAllClientsResponse, error)
	GetAllActuaries(ctx context.Context, in *GetAllActuariesRequest, opts ...grpc.CallOption) (*GetAllActuariesResponse, error)
	GetIdentityByUserId(ctx context.Context, in *GetIdentityByUserIdRequest, opts ...grpc.CallOption) (*GetIdentityByUserIdResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetClientById(ctx context.Context, in *GetClientByIdRequest, opts ...grpc.CallOption) (*GetClientByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientByIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetClientById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetClientByIdentityId(ctx context.Context, in *GetClientByIdentityIdRequest, opts ...grpc.CallOption) (*GetClientByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientByIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetClientByIdentityId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetEmployeeById(ctx context.Context, in *GetEmployeeByIdRequest, opts ...grpc.CallOption) (*GetEmployeeByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeByIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetEmployeeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetEmployeeByIdentityId(ctx context.Context, in *GetEmployeeByIdentityIdRequest, opts ...grpc.CallOption) (*GetEmployeeByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeByIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetEmployeeByIdentityId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllClients(ctx context.Context, in *GetAllClientsRequest, opts ...grpc.CallOption) (*GetAllClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllClientsResponse)
	err := c.cc.Invoke(ctx, UserService_GetAllClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllActuaries(ctx context.Context, in *GetAllActuariesRequest, opts ...grpc.CallOption) (*GetAllActuariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllActuariesResponse)
	err := c.cc.Invoke(ctx, UserService_GetAllActuaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIdentityByUserId(ctx context.Context, in *GetIdentityByUserIdRequest, opts ...grpc.CallOption) (*GetIdentityByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityByUserIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetIdentityByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetClientById(context.Context, *GetClientByIdRequest) (*GetClientByIdResponse, error)
	GetClientByIdentityId(context.Context, *GetClientByIdentityIdRequest) (*GetClientByIdResponse, error)
	GetEmployeeById(context.Context, *GetEmployeeByIdRequest) (*GetEmployeeByIdResponse, error)
	GetEmployeeByIdentityId(context.Context, *GetEmployeeByIdentityIdRequest) (*GetEmployeeByIdResponse, error)
	GetAllClients(context.Context, *GetAllClientsRequest) (*GetAllClientsResponse, error)
	GetAllActuaries(context.Context, *GetAllActuariesRequest) (*GetAllActuariesResponse, error)
	GetIdentityByUserId(context.Context, *GetIdentityByUserIdRequest) (*GetIdentityByUserIdResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetClientById(context.Context, *GetClientByIdRequest) (*GetClientByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientById not implemented")
}
func (UnimplementedUserServiceServer) GetClientByIdentityId(context.Context, *GetClientByIdentityIdRequest) (*GetClientByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientByIdentityId not implemented")
}
func (UnimplementedUserServiceServer) GetEmployeeById(context.Context, *GetEmployeeByIdRequest) (*GetEmployeeByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeById not implemented")
}
func (UnimplementedUserServiceServer) GetEmployeeByIdentityId(context.Context, *GetEmployeeByIdentityIdRequest) (*GetEmployeeByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeByIdentityId not implemented")
}
func (UnimplementedUserServiceServer) GetAllClients(context.Context, *GetAllClientsRequest) (*GetAllClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllClients not implemented")
}
func (UnimplementedUserServiceServer) GetAllActuaries(context.Context, *GetAllActuariesRequest) (*GetAllActuariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllActuaries not implemented")
}
func (UnimplementedUserServiceServer) GetIdentityByUserId(context.Context, *GetIdentityByUserIdRequest) (*GetIdentityByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityByUserId not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetClientById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetClientById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetClientById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetClientById(ctx, req.(*GetClientByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetClientByIdentityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientByIdentityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetClientByIdentityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetClientByIdentityId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetClientByIdentityId(ctx, req.(*GetClientByIdentityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetEmployeeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetEmployeeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetEmployeeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetEmployeeById(ctx, req.(*GetEmployeeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetEmployeeByIdentityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeByIdentityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetEmployeeByIdentityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetEmployeeByIdentityId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetEmployeeByIdentityId(ctx, req.(*GetEmployeeByIdentityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllClients(ctx, req.(*GetAllClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllActuaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllActuariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllActuaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllActuaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllActuaries(ctx, req.(*GetAllActuariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIdentityByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIdentityByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIdentityByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIdentityByUserId(ctx, req.(*GetIdentityByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientById",
			Handler:    _UserService_GetClientById_Handler,
		},
		{
			MethodName: "GetClientByIdentityId",
			Handler:    _UserService_GetClientByIdentityId_Handler,
		},
		{
			MethodName: "GetEmployeeById",
			Handler:    _UserService_GetEmployeeById_Handler,
		},
		{
			MethodName: "GetEmployeeByIdentityId",
			Handler:    _UserService_GetEmployeeByIdentityId_Handler,
		},
		{
			MethodName: "GetAllClients",
			Handler:    _UserService_GetAllClients_Handler,
		},
		{
			MethodName: "GetAllActuaries",
			Handler:    _UserService_GetAllActuaries_Handler,
		},
		{
			MethodName: "GetIdentityByUserId",
			Handler:    _UserService_GetIdentityByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/user.proto",
}
