// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClientByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientByIdRequest) Reset() {
	*x = GetClientByIdRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientByIdRequest) ProtoMessage() {}

func (x *GetClientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientByIdRequest.ProtoReflect.Descriptor instead.
func (*GetClientByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetClientByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetClientByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientByIdResponse) Reset() {
	*x = GetClientByIdResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientByIdResponse) ProtoMessage() {}

func (x *GetClientByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientByIdResponse.ProtoReflect.Descriptor instead.
func (*GetClientByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetClientByIdResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetClientByIdResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetClientByIdResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetEmployeeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdRequest) Reset() {
	*x = GetEmployeeByIdRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdRequest) ProtoMessage() {}

func (x *GetEmployeeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmployeeByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsSupervisor  bool                   `protobuf:"varint,4,opt,name=is_supervisor,json=isSupervisor,proto3" json:"is_supervisor,omitempty"`
	IsAgent       bool                   `protobuf:"varint,5,opt,name=is_agent,json=isAgent,proto3" json:"is_agent,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,6,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	OrderLimit    float64                `protobuf:"fixed64,7,opt,name=order_limit,json=orderLimit,proto3" json:"order_limit,omitempty"`
	UsedLimit     float64                `protobuf:"fixed64,8,opt,name=used_limit,json=usedLimit,proto3" json:"used_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdResponse) Reset() {
	*x = GetEmployeeByIdResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdResponse) ProtoMessage() {}

func (x *GetEmployeeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmployeeByIdResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeByIdResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetEmployeeByIdResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetEmployeeByIdResponse) GetIsSupervisor() bool {
	if x != nil {
		return x.IsSupervisor
	}
	return false
}

func (x *GetEmployeeByIdResponse) GetIsAgent() bool {
	if x != nil {
		return x.IsAgent
	}
	return false
}

func (x *GetEmployeeByIdResponse) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

func (x *GetEmployeeByIdResponse) GetOrderLimit() float64 {
	if x != nil {
		return x.OrderLimit
	}
	return 0
}

func (x *GetEmployeeByIdResponse) GetUsedLimit() float64 {
	if x != nil {
		return x.UsedLimit
	}
	return 0
}

type GetAllClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllClientsRequest) Reset() {
	*x = GetAllClientsRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllClientsRequest) ProtoMessage() {}

func (x *GetAllClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllClientsRequest.ProtoReflect.Descriptor instead.
func (*GetAllClientsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllClientsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllClientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAllClientsRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetAllClientsRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *ClientResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClientResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClientResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ClientResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetAllClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientResponse      `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllClientsResponse) Reset() {
	*x = GetAllClientsResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllClientsResponse) ProtoMessage() {}

func (x *GetAllClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllClientsResponse.ProtoReflect.Descriptor instead.
func (*GetAllClientsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllClientsResponse) GetClients() []*ClientResponse {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *GetAllClientsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllClientsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllClientsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAllClientsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllActuariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActuariesRequest) Reset() {
	*x = GetAllActuariesRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActuariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActuariesRequest) ProtoMessage() {}

func (x *GetAllActuariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActuariesRequest.ProtoReflect.Descriptor instead.
func (*GetAllActuariesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllActuariesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllActuariesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAllActuariesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetAllActuariesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type ActuaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Department    string                 `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	PositionId    uint64                 `protobuf:"varint,7,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	IsAgent       bool                   `protobuf:"varint,9,opt,name=is_agent,json=isAgent,proto3" json:"is_agent,omitempty"`
	IsSupervisor  bool                   `protobuf:"varint,10,opt,name=is_supervisor,json=isSupervisor,proto3" json:"is_supervisor,omitempty"`
	OrderLimit    float64                `protobuf:"fixed64,11,opt,name=order_limit,json=orderLimit,proto3" json:"order_limit,omitempty"`
	UsedLimit     float64                `protobuf:"fixed64,12,opt,name=used_limit,json=usedLimit,proto3" json:"used_limit,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,13,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActuaryResponse) Reset() {
	*x = ActuaryResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActuaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActuaryResponse) ProtoMessage() {}

func (x *ActuaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActuaryResponse.ProtoReflect.Descriptor instead.
func (*ActuaryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ActuaryResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActuaryResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ActuaryResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ActuaryResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActuaryResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ActuaryResponse) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *ActuaryResponse) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *ActuaryResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ActuaryResponse) GetIsAgent() bool {
	if x != nil {
		return x.IsAgent
	}
	return false
}

func (x *ActuaryResponse) GetIsSupervisor() bool {
	if x != nil {
		return x.IsSupervisor
	}
	return false
}

func (x *ActuaryResponse) GetOrderLimit() float64 {
	if x != nil {
		return x.OrderLimit
	}
	return 0
}

func (x *ActuaryResponse) GetUsedLimit() float64 {
	if x != nil {
		return x.UsedLimit
	}
	return 0
}

func (x *ActuaryResponse) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

type GetAllActuariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actuaries     []*ActuaryResponse     `protobuf:"bytes,1,rep,name=actuaries,proto3" json:"actuaries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllActuariesResponse) Reset() {
	*x = GetAllActuariesResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllActuariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllActuariesResponse) ProtoMessage() {}

func (x *GetAllActuariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllActuariesResponse.ProtoReflect.Descriptor instead.
func (*GetAllActuariesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllActuariesResponse) GetActuaries() []*ActuaryResponse {
	if x != nil {
		return x.Actuaries
	}
	return nil
}

func (x *GetAllActuariesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllActuariesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllActuariesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAllActuariesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\auser.v1\"&\n" +
	"\x14GetClientByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Z\n" +
	"\x15GetClientByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"(\n" +
	"\x16GetEmployeeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x81\x02\n" +
	"\x17GetEmployeeByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12#\n" +
	"\ris_supervisor\x18\x04 \x01(\bR\fisSupervisor\x12\x19\n" +
	"\bis_agent\x18\x05 \x01(\bR\aisAgent\x12#\n" +
	"\rneed_approval\x18\x06 \x01(\bR\fneedApproval\x12\x1f\n" +
	"\vorder_limit\x18\a \x01(\x01R\n" +
	"orderLimit\x12\x1d\n" +
	"\n" +
	"used_limit\x18\b \x01(\x01R\tusedLimit\"\x83\x01\n" +
	"\x14GetAllClientsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"\xe3\x01\n" +
	"\x0eClientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"\xb2\x01\n" +
	"\x15GetAllClientsResponse\x121\n" +
	"\aclients\x18\x01 \x03(\v2\x17.user.v1.ClientResponseR\aclients\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x85\x01\n" +
	"\x16GetAllActuariesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"\x8d\x03\n" +
	"\x0fActuaryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"department\x18\x06 \x01(\tR\n" +
	"department\x12\x1f\n" +
	"\vposition_id\x18\a \x01(\x04R\n" +
	"positionId\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12\x19\n" +
	"\bis_agent\x18\t \x01(\bR\aisAgent\x12#\n" +
	"\ris_supervisor\x18\n" +
	" \x01(\bR\fisSupervisor\x12\x1f\n" +
	"\vorder_limit\x18\v \x01(\x01R\n" +
	"orderLimit\x12\x1d\n" +
	"\n" +
	"used_limit\x18\f \x01(\x01R\tusedLimit\x12#\n" +
	"\rneed_approval\x18\r \x01(\bR\fneedApproval\"\xb9\x01\n" +
	"\x17GetAllActuariesResponse\x126\n" +
	"\tactuaries\x18\x01 \x03(\v2\x18.user.v1.ActuaryResponseR\tactuaries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages2\xd9\x02\n" +
	"\vUserService\x12N\n" +
	"\rGetClientById\x12\x1d.user.v1.GetClientByIdRequest\x1a\x1e.user.v1.GetClientByIdResponse\x12T\n" +
	"\x0fGetEmployeeById\x12\x1f.user.v1.GetEmployeeByIdRequest\x1a .user.v1.GetEmployeeByIdResponse\x12N\n" +
	"\rGetAllClients\x12\x1d.user.v1.GetAllClientsRequest\x1a\x1e.user.v1.GetAllClientsResponse\x12T\n" +
	"\x0fGetAllActuaries\x12\x1f.user.v1.GetAllActuariesRequest\x1a .user.v1.GetAllActuariesResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(*GetClientByIdRequest)(nil),    // 0: user.v1.GetClientByIdRequest
	(*GetClientByIdResponse)(nil),   // 1: user.v1.GetClientByIdResponse
	(*GetEmployeeByIdRequest)(nil),  // 2: user.v1.GetEmployeeByIdRequest
	(*GetEmployeeByIdResponse)(nil), // 3: user.v1.GetEmployeeByIdResponse
	(*GetAllClientsRequest)(nil),    // 4: user.v1.GetAllClientsRequest
	(*ClientResponse)(nil),          // 5: user.v1.ClientResponse
	(*GetAllClientsResponse)(nil),   // 6: user.v1.GetAllClientsResponse
	(*GetAllActuariesRequest)(nil),  // 7: user.v1.GetAllActuariesRequest
	(*ActuaryResponse)(nil),         // 8: user.v1.ActuaryResponse
	(*GetAllActuariesResponse)(nil), // 9: user.v1.GetAllActuariesResponse
}
var file_user_proto_depIdxs = []int32{
	5, // 0: user.v1.GetAllClientsResponse.clients:type_name -> user.v1.ClientResponse
	8, // 1: user.v1.GetAllActuariesResponse.actuaries:type_name -> user.v1.ActuaryResponse
	0, // 2: user.v1.UserService.GetClientById:input_type -> user.v1.GetClientByIdRequest
	2, // 3: user.v1.UserService.GetEmployeeById:input_type -> user.v1.GetEmployeeByIdRequest
	4, // 4: user.v1.UserService.GetAllClients:input_type -> user.v1.GetAllClientsRequest
	7, // 5: user.v1.UserService.GetAllActuaries:input_type -> user.v1.GetAllActuariesRequest
	1, // 6: user.v1.UserService.GetClientById:output_type -> user.v1.GetClientByIdResponse
	3, // 7: user.v1.UserService.GetEmployeeById:output_type -> user.v1.GetEmployeeByIdResponse
	6, // 8: user.v1.UserService.GetAllClients:output_type -> user.v1.GetAllClientsResponse
	9, // 9: user.v1.UserService.GetAllActuaries:output_type -> user.v1.GetAllActuariesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
