name: Integration Tests
run-name: Integration tests for ${{ github.repository }}

on:
  workflow_dispatch:
  push:

jobs:
  integration-tests:
    name: Integration tests ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - ./common
          - ./services/banking-service
          - ./services/trading-service
          - ./services/user-service

    steps:
    - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: './go.work'
        cache-dependency-path: '**/go.mod'
    
    - name: Run integration tests for ${{ matrix.target }}
      run: go test -tags=integration -v ${{ matrix.target }}/...
